/*
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar: [{ type: 'autogenerated', dirName: '.' }],
  // But you can create a sidebar manually
  docs: [
    {
      type: 'category',
      label: '👋  WELCOME',
      collapsed: true,
      items: [
        'intro/getting-started/index',
        'intro/overview/index',
        'intro/what-is-datree/index',
      ],
    },
    {
      type: 'category',
      label: '🛠️  SETUP',
      collapsed: true,
      items: [
        'setup/centralized-policy/index',
        'setup/schema-validation/index',
        'setup/policy-as-code/index',
        'setup/cli-output/index',
        'setup/cli-arguments/index',
        'setup/history/index',
        'setup/account-token/index',
      ],
    },
    {
      type: 'category',
      label: '🚔  BUILT-IN RULES',
      link: {
        type: 'doc',
        id: 'built-in-rules/index',
      },
      collapsed: true,
      items: [
        'built-in-rules/containers/index',
        'built-in-rules/Workload/index',
        'built-in-rules/cronjob/index',
        'built-in-rules/networking/index',
        'built-in-rules/security/index',
        'built-in-rules/Deprecation/index',
        'built-in-rules/argo/index',
        'built-in-rules/other/index',
      ],
    },
    {
      type: 'category',
      label: '🤖  CUSTOM RULES',
      collapsed: true,
      items: [
        'custom-rules/custom-rules-overview/index',
        'custom-rules/basic-examples/index',
        'custom-rules/multiple-property-paths/index',
        'custom-rules/resource-quotas/index',
      ],
    },
    {
      type: 'category',
      label: '🔌  OFFICIAL INTEGRATIONS',
      link: {
        type: 'doc',
        id: 'official-integrations/index',
      },
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'Kubectl plugin',
          href: 'https://github.com/datreeio/kubectl-datree',
        },
        {
          type: 'link',
          label: 'Github action',
          href: 'https://github.com/datreeio/action-datree',
        },
        {
          type: 'link',
          label: 'Helm plugin',
          href: 'https://github.com/datreeio/helm-datree',
        },
        'official-integrations/kustomize-support/index',
        'official-integrations/git-hooks/index',
        'official-integrations/pre-commit-hook/index',
      ],
    },
    {
      type: 'category',
      label: '🙌  COMMUNITY INTEGRATIONS',
      link: {
        type: 'doc',
        id: 'community-integrations/index',
      },
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'VSCode plugin',
          href: 'https://github.com/SuyashSonawane/vscode-datree',
        },
      ],
    },
    {
      type: 'category',
      label: '⏩  CI/CD EXAMPLES',
      link: {
        type: 'doc',
        id: 'cicd-examples/index',
      },
      collapsed: true,
      items: [
        'cicd-examples/circle-ci/index',
        'cicd-examples/travis-ci/index',
        'cicd-examples/gitlab-cicd/index',
        'cicd-examples/jenkins-pipeline/index',
      ],
    },
    {
      type: 'doc',
      label: '💬  FAQ',
      id: 'faqs/index',
    },
    {
      type: 'doc',
      label: '🗃️  TROUBLESHOOTING',
      id: 'troubleshooting/index',
    },
    {
      type: 'link',
      label: '📚  RESOURCES',
      href: 'https://github.com/datreeio/awesome-datree/blob/main/README.md',
    },
  ],
};

module.exports = sidebars;
